### ISSUE TITLE
Rename `Steem` to `Knowledgr`

### ISSUE THREAD

**Issue by blockplus** [norestlabs/colab#5]
Rename all instances of Steem to Knowledgr in the project. Note that Steem -> Knowledgr and steem -> knowledgr. Project should continue to compile afterwards.

**Comment by gedanziger** [comment]
@blockplus Note that they might change name again, let's wait until tuesday until they decide completely.

**Comment by blockplus** [comment]
@gedanziger 
So they didn't determine to change `colab` to `knowledgr` yet?

**Comment by gedanziger** [comment]
They switched it, they are thinking for switch back. We will find it out soon.

**Comment by blockplus** [comment]
As we should go ahead for further development, we are gonna change name as `colab` first and start developing features
